#This compose file adds ProjectSend Application Dashboard https://www.projectsend.org/ to your stack
version: '3.5'
services:
  reverse-proxy:
    networks:
      - projectsend
  mail-relay:
    networks:
      - projectsend
  projectsend:
    image: linuxserver/projectsend:latest
    container_name: projectsend
    volumes:
      - projectsend-config:/config
      - projectsend-data:/data
    environment:
      - MAX_UPLOAD=8000 #MB default: 5000
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${PROJECTSEND_DOMAIN:?Please copy template.env to .env and provide provide a value for PROJECTSEND_DOMAIN}
      - traefik.docker.network=projectsend
      - traefik.default.protocol=http
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - projectsend
    restart: unless-stopped
    depends_on:
      - projectsend-db
  projectsend-db:
    image: mariadb:latest
    container_name: projectsend-db
    #after starting project send, go to send.yourDynamicDomain.duckdns.org/install/make-config.php
    #to configure projectsend with the database info you provide here. The database host will be
    #"projectsend-db", type will be mySQL, make sure to change the System URI (second page) to start
    #with https:// or else the page will be bare and the site will not work
    environment:
      - MYSQL_DATABASE=projectsend
      - MYSQL_USER=${PROJECT_SEND_DB_USERNAME:-projectsend}
      - MYSQL_PASSWORD=${PROJECT_SEND_DB_PASSWORD:??Please copy template.env to .env and provide provide a value for PROJECT_SEND_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PROJECT_SEND_DB_ROOT_PASSWORD:?Please copy template.env to .env and provide provide a value for PROJECT_SEND_DB_ROOT_PASSWORD}
    volumes:
      - projectsend-database:/var/lib/mysql
    labels:
      - "traefik.enable=false"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    networks:
      - projectsend

networks:
  projectsend:

volumes:
  projectsend-config:
  projectsend-data:
  projectsend-database:
